services:

  calvin-api:
    build:
      context: .
      dockerfile: calvin-api.dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app

  calvin-api-docs:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - calvin-api
