services:
  api:
    build:
      context: .
      dockerfile: calvin-api.dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    environment:
      DB_DSN: "postgres://calvinuser:calvinpass@postgres_db:5432/calvindb?sslmode=disable"
    depends_on:
      postgres_db:
        condition: service_healthy

  api-docs:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - api

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db_calvin
    environment:
      POSTGRES_USER: calvinuser
      POSTGRES_PASSWORD: calvinpass
      POSTGRES_DB: calvindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U calvinuser -d calvindb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
