services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017" # Maps MongoDB default port
    volumes:
      - mongodb_data:/data/db # Persistent storage
      - mongodb_config:/data/configdb # Persistent config

  contacts-manager-api:
    build:
      context: .
      dockerfile: contacts-manager.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  contacts-manager-api-docs:
    build:
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - contacts-manager-api

volumes:
  mongodb_data:
  mongodb_config:
